PIVX Mac Openssl 1.1 fix
This will require some debugging

  CXX      libbitcoin_server_a-rpcserver.o
rpcserver.cpp:654:27: error: no matching constructor for initialization of 'ssl::context'
    rpc_ssl_context = new ssl::context(*rpc_io_service, ssl::context::sslv23);
                          ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate constructor not viable: requires single argument 'm', but 2 arguments were provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/impl/context.ipp:371:10: note: candidate constructor not viable: requires single argument 'other', but 2 arguments were provided
context::context(context&& other)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class context
      ^
rpcserver.cpp:676:50: error: no member named 'impl' in 'boost::asio::ssl::context'
        SSL_CTX_set_cipher_list(rpc_ssl_context->impl(), strCiphers.c_str());
                                ~~~~~~~~~~~~~~~  ^
rpcserver.cpp:559:110: error: no member named 'get_io_service' in 'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>'
    boost::shared_ptr<AcceptedConnectionImpl<Protocol> > conn(new AcceptedConnectionImpl<Protocol>(acceptor->get_io_service(), context, fUseSSL));
                                                                                                   ~~~~~~~~  ^
rpcserver.cpp:732:13: note: in instantiation of function template specialization 'RPCListen<boost::asio::ip::tcp, boost::asio::executor>' requested here
            RPCListen(acceptor, *rpc_ssl_context, fUseSSL);
            ^
3 errors generated.
make[2]: *** [libbitcoin_server_a-rpcserver.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1